apollo:
  bootstrap:
    enabled: true
    namespaces: application,authorization
  meta: http://localhost:8080

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ghrk.paramgovernance.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: provider
    qos-enable: true # 是否开启QOS
    qos-port: 22222 # QOS端口默认端口
    qos-accept-foreign-ip: false # 是否允许QOS请求

